language: java

dist: trusty

addons:
    sonarcloud:
        organization: "farao-community"
        token:
            secure: ${SONAR_TOKEN}

install:
    # Build farao-core
    - git clone https://github.com/farao-community/farao-core farao-community/farao-core
    - pushd farao-community/farao-core && mvn --batch-mode -DskipTests install && popd

script:
- mvn --batch-mode clean verify sonar:sonar
