#!/bin/bash

# Copyright (c) 2018, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

if [ -z $JAVA_HOME ]; then
    JAVA_BIN=`which java 2> /dev/null`
    if [ $? -ne 0 ]; then
        echo "Unable to find java" >&2
        exit -1
    fi
else
    JAVA_BIN=$JAVA_HOME/bin/java
fi

installBinDir=$(dirname $(readlink -f $0))
installDir=${installBinDir%/*}

[ -z "$java_xmx" ] && java_xmx=8G

$JAVA_BIN \
-Xmx$java_xmx \
-cp "$installDir/share/java/*" \
com.farao_community.farao.app.Main "${args[@]}"
